### ISSUE TITLE
[Core/Quest] - Npc Crash Server

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#104]
**Operating system:** Ubuntu 18

**Current behavior :** When talking to npc to deliver the quest the crasha server
That was after the Restructuring

NPC ID = 17807
Quest ID =  9690 [The Second Trial]

Quest Class Paladin Horde

**Comment by coolzoom** [comment]
.go creature 63509
.quest add 9690 
the eversong_woods.cpp has some conversion error 
https://github.com/talamortis/OregonCore/pull/111 i just fix some issue happened during restruction but it may fix the issue
