### ISSUE TITLE
Dungeon/ Old Hillsbrand Foothilis TBC -  Thrall not start

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#105]
**Operating system:** Ubuntu 18

**Current behavior** : Thrall does not start to leave the cage, makes all extra dg content impossible

https://cdn.discordapp.com/attachments/631656058682867712/657430122894327828/Screenshot_451.png - SS

worked before the restructuring

**Comment by coolzoom** [comment]
#115  please test

**Comment by yuanf225** [comment]
@auroralima Need your test confirmation
