### ISSUE TITLE
GCD resets but can't spell again

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#106]
**Operating system:** Ubuntu 18 
GCD should cancel after walking or catching interruption, but it doesn't happen after walking, GCD cancels, but looks like "Spell is not ready yet" even though GCD

Link error recording > https://streamable.com/lrzk1

link to how it should work - Warmane - https://streamable.com/0ujgy

http://www.wowwiki.com/Cooldown 
"If a spell with casting time is interrupted before it has finished casting, the global cooldown will be canceled, meaning you can start casting a new one immediately."

**Comment by wizzymore** [comment]
@auroralima if you still around, test this and let me know if it is okay now

**Comment by auroralima** [comment]
Ok, I will test and put the details here

**Comment by vhiperdev** [comment]
@wizzymore Good job, now seems to work properly on my test!
welcome to oregoncore.

**Comment by talamortis** [comment]
Once tested I will merge into repo, thanks again @wizzymore for fix  and @auroralima for testing.
