### ISSUE TITLE
CRITICAL! Crash Server when enable WARDEN in config (last clean core without any patch!)

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#110]
**Describe the bug**
CRITICAL! Crash Server when enable WARDEN in config (last clean core without any patch!)

**To Reproduce**
Just "Warden.Enabled = 1" and you can not connect to the server - CRASH

**Comment by talamortis** [comment]
Will test when I get home. Thanks for the report.

**Comment by coolzoom** [comment]
i can repeat this, do we have to upgrade openssl to 1.1?

**Comment by PadreWoW** [comment]
I use OpenSSL 1.1.1d, CMAKE 3.16.2, MS Visual Studio 2015 and MS Visual Studio 2019 (tested on both)

With "Warden.Enabled = 1" can not connect to server - CRASH
With "Warden.Enabled = 0" can connect

**Comment by coolzoom** [comment]
im using version 1.0.2 and VS2017 also repeat same as yours

**Comment by coolzoom** [comment]
tested error gone after revert pr #107 , may need fix for this pr

**Comment by yuanf225** [comment]
yes,this is a very serious problem

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/OregonCoreLegacy/commit/161031d2f7cac11c07748bd9dcf85fc44ea69232

**Comment by PadreWoW** [comment]
REMOVE WARDEN?????
Is this your solution to the problem?
ARE YOU JOKING?

Cheaters will crush your server every 5 min with huge number of packets

**Comment by talamortis** [comment]
I will test the issue and see if I can find a alternative to fix instead of removing warden.

**Comment by ReyDonovan** [comment]
@talamortis I cut out the old non-worthy version))) to add the Warden + Passive)

**Comment by PadreWoW** [comment]
I see only CUT, but no ADD

**Comment by talamortis** [comment]
Ok, i managed to get the player to log into the world, But upon player logout it was causing crash. Will revert #107 till we come up with a better solution.

**Comment by ReyDonovan** [comment]
pls debug mode -> crashe logs

**Comment by talamortis** [comment]
what version of openssl are you using?
