### ISSUE TITLE
[Core/Logs] Logs not generating logs

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#113]
**Operating system:** Ubuntu 18

**Current behavior :** 
Even enabled log reporting in [oregoncore.conf] is not generating logs
gm_commands example

![image](https://user-images.githubusercontent.com/46387591/71382913-d3739900-25b8-11ea-9a43-ea1351be67e0.png)

**AC HASH/COMMIT: Branch: Eluna:**
https://github.com/talamortis/OregonCore/commit/132190d6d57be00ef27117da6db28d3108091430

**Comment by PadreWoW** [comment]
not confirmed
all logs are fine
just open file and you'll see

**Comment by diluh** [comment]
The file is generated but it has no content see in the photo the file size [0 kb]

@PadreWoW

**Comment by PadreWoW** [comment]
Just OPEN file and you will see content
Example from my server:

![image](https://user-images.githubusercontent.com/6802530/71403515-05304280-2641-11ea-9a07-f11d1b4695a1.png)

**Comment by diluh** [comment]
You do not understand, some files are not registering anything ..

- gm commands.logs
- characters.logs

are not all of the photo

@PadreWoW

**Comment by PadreWoW** [comment]
Not confirmed:

![image](https://user-images.githubusercontent.com/6802530/71404449-9ef8ef00-2643-11ea-83a7-bf5346a53cce.png)

**Comment by diluh** [comment]
Have your logging configuration in [oregoncore.conf] and your [ac/hash commit] please.
@PadreWoW

**Comment by PadreWoW** [comment]
Commit:

Author:			coolzoom <tommingc@Gmail.com>
Commit hash:	8e859b170b2f0653edd85baca31db4fc3e24d9a3
Child:			ef56c9b42f
Parent:			6bc3538248

**Comment by PadreWoW** [comment]
PidFile = ""
LogMask = 4083
LogFile = "server.log"
ChatLogFile = "chat.log"
LogTimestamp = 0
WorldLogFile = ""
DBErrorLogFile = "db_errors.log"
CharLogFile = "characters.log"
CharLogTimestamp = 0
GmLogFile = "gm_commands.log"
GmLogTimestamp = 0
GmLogPerAccount = 0
RaLogFile = ""
ArenaLogFile = "arena.log"
ArenaLogExtendedInfo = 1
LogColors = "14 11 4 3 1 1 2 7 5 0 4 0 1 3 2 4 0"
DBLogMask = 2
LogSQLFilename = "logSQL.sql"
LogSQLTimestamp = 0
ChatLogs.Channel      = 1
ChatLogs.SysChan      = 1
ChatLogs.Whisper      = 1
ChatLogs.Party        = 1
ChatLogs.Raid         = 1
ChatLogs.Guild        = 1
ChatLogs.Public       = 1
ChatLogs.Addon        = 0
ChatLogs.BattleGround = 1
ChatLogTimestamp = 0

**Comment by PadreWoW** [comment]
A little clarification - my server is on Windows Server 2016 not Linux
OpenSSL 1.1.1d, Cmake 3.16.2, MS Visual Studio 2019 Community

**Comment by diluh** [comment]
With its configuration the logs now work are logging.
@PadreWoW  thanks

I'll be closing this problem, if someone is with the same problem will check this setting.
