### ISSUE TITLE
Quest - Triage ID 6622 Prof - First Aid 

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#119]
**Operating system:** Ubuntu 18

**Current behavior :** Quest Required to advance First Aid Up, you receive an item Triage Bandage - ID 16991
You have to use them in an npcs to save them, the bug is that they are like enemies, and they will quickly lose life until they die.

**Was expected to** : https://www.youtube.com/watch?v=vdMoa9S7O5g

**Comment by talamortis** [comment]
Fixed in https://github.com/talamortis/OregonCore/commit/a96f1abd0a91db175874a666b48d97b0b63fa5cd
