### ISSUE TITLE
Magister Terrace BOSS Priestess Delrissa ID - 24560

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#121]
**Operating system:** Ubuntu 18

**Current behavior** The boss can't pass an "invisible" wall.
and after dying he appears again.
This happens in both difficulties.
The npcs around it also do the same.

video bug  - https://streamable.com/2wd40

**Comment by talamortis** [comment]
will work on this issue tonight, I know where the error is coming from :)

Update:

Due to the "invisible wall" it resets the boss so they spawn an extra add. this is whats causing the issue with the loot. I will need more time to look into pathing

**Comment by coolzoom** [comment]
.go creature 96966
please test
![image](https://user-images.githubusercontent.com/10232727/73596065-0450d180-455a-11ea-9a6c-c3e68e49722a.png)
