### ISSUE TITLE
Quest Death's Door ID -  10910

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#125]
**Operating system:** Ubuntu 18

**Current behavior**  : 

you get an item, that when you use it, the npc comes to you, this npc is that you give him the quest, but when using it the npc doesn't come

link quest worked https://www.youtube.com/watch?v=nCYkkNnN7uA

**Comment by talamortis** [comment]
Fixed in https://github.com/talamortis/OregonCore/commit/77be065347fbd403e933f42be75acd981b83f07d
