### ISSUE TITLE
[Core/Raid] Reset of Instance in days does not work

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#128]
**Operating system:** Ubuntu 18

**Current behavior :**

I tried to change by increasing the days of Raid Recharge and found that it does not work, the value never changes regardless of whether the amount is greater or less at: `Rate.InstanceResetTime = 1`
oregon-core.conf

Until today I can't change the reset time of the raids, I think it's not working correctly I tried to change all the ways and manual and it always goes back to the default of 1 day
Help me, maybe I'm doing something wrong or not.
**`1579492800 = 1 day`**
characters table = instance_reset

![image](https://user-images.githubusercontent.com/46387591/73611636-912f7580-45c2-11ea-8193-b414c33e0a45.png)

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/73685266-c2d93700-46bd-11ea-9b3b-f9968b947c67.png)

Done a temp fix but not implemented the config file yet. Im going to make it so the raids reset on a certain day instead of using timestamps
