### ISSUE TITLE
Bug with Explosive Sheep (item id = 4384)

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#132]
**Describe the bug**
When you use Explosive Sheep there is NO cooldown - you can not use other sheeps or even goblin mine - they are greyed out without cooldown timer

**Comment by wizzymore** [comment]
Confirming, this can be used again only if you relog.

**Comment by wizzymore** [comment]
I think i got to the source of the problem, i think this happens because of the packets sent to the client don’t have the right structure for items, the spell works okay, the item doesn’t
