### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by ekzobam** [talamortis/OregonCore#133]
**Describe the bug**

Server crashed when send chat any command, example .help or .commands or .qwerty

**To Reproduce**
1.  Start server
2. Login in game
3. Send any command
4. profit!

**Additional context**

[Crash report on Pastebin](https://pastebin.com/Zc3uM8u9)

The crashes started after applying this commit https://github.com/talamortis/OregonCore/commit/37f937c9599c278a70ab4152c5cab67674462b32
I have Talamortis core with small changes (example NameLink in chat). Server crashed only Linux (debian os), on win7 and win10 work perfectly.

**Comment by kuramajssken001** [comment]
GetNameLink().c_str()

**Comment by ekzobam** [comment]
> GetNameLink().c_str()

As I understand it, the crash comes from `SetDataForCommandInTable`, `GetNameLink()` has no effect on this

**Comment by left3721** [comment]
I have encountered this error

**Comment by talamortis** [comment]
Thanks for reporting, i will test now - currently compiling on my VPS in debug mode to test

**Comment by talamortis** [comment]
could you please test recent commit

**Comment by ekzobam** [comment]
> could you please test recent commit

so far, server not crash

**Comment by talamortis** [comment]
Thanks for testing will close issue now 👍

**Comment by LordPsyan** [comment]
I just pulled fresh, compiled ElunaCFBG branch. It crashes on any command still.

commit 33e903dec25abbd009efdb0a636bc3ff27759db6 (HEAD -> ElunaCFBG, origin/ElunaCFBG)

**Comment by yuanf225** [comment]
> I just pulled fresh, compiled ElunaCFBG branch. It crashes on any command still.
> 
> 
> 
> commit 33e903dec25abbd009efdb0a636bc3ff27759db6 (HEAD -> ElunaCFBG, origin/ElunaCFBG)


Is there any error message?

**Comment by LordPsyan** [comment]
crash report here:
https://pastebin.com/ZzDh3h65
does the same thing with master branch.

**Comment by talamortis** [comment]
Yes, its since we implemented the new command PR, it only happens on linux due to string being null. trying to still figure out how to fix this.
