### ISSUE TITLE
access_requirement not working

### ISSUE THREAD

**Issue by turbosnek** [talamortis/OregonCore#143]
Hi, I have a problem with access_requirement. I don' have complete quest Hard to Kill to enter Magister terrace HC, but I can enter. My GM mode is off.

Struck my DB table

INSERT INTO access_requirement (id, level_min, level_max, item, item2, heroic_key, heroic_key2, quest_done, quest_failed_text, heroic_quest_done, heroic_quest_failed_text, comment) VALUES ('51', '70', '0', '0', '0', '0', '0', '0', NULL, '11492', 'Heroic Difficulty requires completion of the \"Hard to Kill\" quest.', 'instance Magisters\' Terrace (585)')

Sorry for my English. I am Czech

**Comment by talamortis** [comment]
can't reproduce anyone else confirm before i close?

**Comment by wizzymore** [comment]
Working as intended for me as well

https://i.imgur.com/se59GmS.jpg

**Comment by talamortis** [comment]
Thank you, will close issue as can not reproduce.
