### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by turbosnek** [talamortis/OregonCore#145]
Hello guys, I downloaded new core from https://github.com/talamortis/OregonCore and I have compilation error.

16>..\..\..\OregonCore\src\shared\Debugging\WheatyExceptionReport.cpp(1338): warning C4477: 'sprintf' : format string '%X' requires an argument of type 'unsigned int', but variadic argument 1 has type 'PDWORD'
16>..\..\..\OregonCore\src\shared\Debugging\WheatyExceptionReport.cpp(1349): warning C4477: 'sprintf' : format string '%X' requires an argument of type 'unsigned int', but variadic argument 1 has type 'PDWORD'

Can you help me how to fix it?

I use VS 2015

**Comment by talamortis** [comment]
These are warning, this shouldn't effect the compile of the source.

**Comment by turbosnek** [comment]
OK and this? 
5>TRACKER : error TRK0005: Failed to locate: "rc.exe"

**Comment by talamortis** [comment]
did you tick MSBuild in individual components when installing Visual studio?

**Comment by turbosnek** [comment]
I reinstaled VS and now error with mysql.
Cannot read libmysql.dll

**Comment by talamortis** [comment]
[mysql_lib.zip](https://github.com/talamortis/OregonCore/files/4582139/mysql_lib.zip)

use these :)

**Comment by turbosnek** [comment]
3>C:\mysql-5.6.47-win32\lib\libmysql.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2D8
4>C:\mysql-5.6.47-win32\lib\libmysql.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2D8

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/81091307-f4e57980-8ef6-11ea-9a82-5a4c8ee17ad5.png)

**Comment by turbosnek** [comment]
error with libmysql. I reinstall all programs and write

**Comment by ekzobam** [comment]
@talamortis,  I will not create another task, help with a compilation error.
Core without modules compile is succesful, but i added some modules, got some error. 
`GenLoader.cpp:(.text+0x30): undefined reference to `AddSC_WorldChatScripts()'`
I use: cmake, then make.

**Comment by talamortis** [comment]
which branch are you using? and what module are you compiling?

**Comment by ekzobam** [comment]
@talamortis i use fork with master branch,
Modules: Boss Announcer, Chat censure and another not pulled in your repo.  Until some time, it compiled successfully.
OS: Debian 9, 32bit

```
[ 99%] Linking CXX executable oregon-core
../scripts/libscripts.a(GenLoader.cpp.o): In function `AddWorldChatScripts()':
GenLoader.cpp:(.text+0x10): undefined reference to `AddSC_WorldChatScripts()'
../scripts/libscripts.a(GenLoader.cpp.o): In function `AddModuleScripts()':
GenLoader.cpp:(.text+0x30): undefined reference to `AddSC_WorldChatScripts()'
GenLoader.cpp:(.text+0x35): undefined reference to `AddWhoLoggedScripts()'
```

**Comment by talamortis** [comment]
Are the modules working as intended?

**Comment by turbosnek** [comment]
After reinstaling all programs I have this problem.


![vs2015_1](https://user-images.githubusercontent.com/695608/81113456-8f0de780-8f20-11ea-9c45-358910753d1a.png)

![vs2015_2](https://user-images.githubusercontent.com/695608/81113494-9c2ad680-8f20-11ea-9563-44613c9c1631.png)

![vs2015_3](https://user-images.githubusercontent.com/695608/81113506-a056f400-8f20-11ea-8507-e45b268c855b.png)

![vs2015_4](https://user-images.githubusercontent.com/695608/81113513-a4831180-8f20-11ea-8a99-1a87bd0c163e.png)

**Comment by talamortis** [comment]
Message me on discord speedfangz#6864
