### ISSUE TITLE
Hunter's traps

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#150]
1. Hunter traps after installation remain visible, but they must be invisible. Traps can be found at close range using stealth detection spells like Detect Traps (https://classic.wowhead.com/spell=2836/detect-traps).
2. When traps are activated in stealth mode (by rogue or druid for example), the traps do not work, they just disappear.

https://www.youtube.com/watch?v=gQbUqkJUZzs

**Comment by talamortis** [comment]
Fixed in https://github.com/talamortis/OregonCore/commit/daf7087061f60044235f05688c654b6a81699245
