### ISSUE TITLE
Players can fly without mount

### ISSUE THREAD

**Issue by d3athbl0w** [talamortis/OregonCore#153]
**Revision**:
4298
**Operating system**:
Windows server 2016
**Current behavior**: 

Characters can fly without mounts and it is not hack

**Expected behavior**: 
...

**Steps to reproduce the problem**:
At least 15% to 30% of the time they can do that, users just dismount and can fly without mounts ...

![WhatsApp Image 2020-05-18 at 3 21 35 AM](https://user-images.githubusercontent.com/14060040/82185829-d6e52500-98b7-11ea-8d6e-916ba1fd9973.jpeg)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Any idea how to reproduce this issue? as i have not come across this yet.

**Comment by PadreWoW** [comment]
I can confirm it (this is very old bug)

Try my patch to fix it:

[Patch.txt](https://github.com/talamortis/OregonCore/files/4695582/Patch.txt)

**Comment by PadreWoW** [comment]
https://www.youtube.com/watch?v=cHn8WcmE5FA

**Comment by PadreWoW** [comment]
Any news?

**Comment by talamortis** [comment]
The patch is a hackfix, sorry, but I will take a look at it when I have a bit more time, this is due to aura apply/unapply

**Comment by talamortis** [comment]
fixed in : https://github.com/talamortis/OregonCore/commit/0fed2a63fe2dd0617a7d0a172b161f5a3a119a30
