### ISSUE TITLE
Core crash

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#155]
OS：Ubuntu16.04
version：ElunaCFBG
As long as the command is used in the console, it will crash. I can't get the log, only the screenshot
![image](https://user-images.githubusercontent.com/43561197/83273809-82b73a80-a1ff-11ea-8dca-d824f0cf2ff3.png)
![image](https://user-images.githubusercontent.com/43561197/83273857-8fd42980-a1ff-11ea-811a-37495c6ba666.png)
![image](https://user-images.githubusercontent.com/43561197/83273894-9b275500-a1ff-11ea-85bf-e98aa7cac345.png)
![image](https://user-images.githubusercontent.com/43561197/83273921-a67a8080-a1ff-11ea-979f-5d9a3b6a6de4.png)
![image](https://user-images.githubusercontent.com/43561197/83273938-ae3a2500-a1ff-11ea-9fe0-72feedc5ec26.png)
![image](https://user-images.githubusercontent.com/43561197/83273965-b5f9c980-a1ff-11ea-8b32-9dd16e578780.png)
![image](https://user-images.githubusercontent.com/43561197/83273980-be520480-a1ff-11ea-878e-a49c5d2345b1.png)
![image](https://user-images.githubusercontent.com/43561197/83274009-c6aa3f80-a1ff-11ea-8b87-936674c19d09.png)
![image](https://user-images.githubusercontent.com/43561197/83274030-cf027a80-a1ff-11ea-960c-c35c7c0e70c9.png)
![image](https://user-images.githubusercontent.com/43561197/83274049-d4f85b80-a1ff-11ea-9948-e6d26a651d6f.png)

**Comment by talamortis** [comment]
fixed: https://github.com/talamortis/OregonCore/commit/9aaa3454c28b63e1cff100dbc0c5aeefbf95c803
