### ISSUE TITLE
pinfo command and npc follow

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#156]
**Revision**:
8d8e52d
**Operating system**:
Win 7 x64
**Current behavior**: 
....
Command .pinfo, used in-game, crashes the server.
Command .npc follow not work - npc stay in his place.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
i cant reproduce the issue with the pinfo command but manage to find the error on the npc follow. 

are you able to share debug crash log? 

Thanks

**Comment by talamortis** [comment]
Can anyone else confirm this issue with the pinfo command??

**Comment by CTPEJIOK84** [comment]
This problem only with .pinfo command.

Send crash log. 
[4368_oregon-core.exe_[5-6_20-4-0].txt](https://github.com/talamortis/OregonCore/files/4739691/4368_oregon-core.exe_.5-6_20-4-0.txt)

**Comment by talamortis** [comment]
could you compile in debug and then send it?

Thanks.

**Comment by yuanf225** [comment]
onight I can find time to verify it in Debug mode

**Comment by CTPEJIOK84** [comment]
The problem is resolved. It was my localization error in oregon_string.
Sory for wasted time.

**Comment by talamortis** [comment]
Ok thank you, i will close this issue
