### ISSUE TITLE
Mana Tap should only works on manausers

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#158]
**Describe the bug**
Mana Tap should only works on manausers, but now it works on ALL type of mobs (even without mana bar)

**To Reproduce**
1. Just create Blood Elf and see the bug
2. 
3. 
4. 

**Expected behavior**
 - Mana Tap breaks Polymorph, Sap, and Freezing Trap as the mana drain counts as an attack.
 - Since Mana Tap costs zero mana, it's good to use mana tap as quickly as possible, remembering that arcane energy stacks up to 3 times.
 - An enemy that has run out of mana will have any remaining mana drained up to the maximum of the ability.
 - Doesn't work on enemies with no mana bar.
 - Can be used to pull mobs efficiently if you lack any other means.
 - Mana tap activates the GCD. 

https://wowwiki.fandom.com/wiki/Mana_Tap

**Branch**
master

**Comment by ReyDonovan** [comment]
it is surprising that in 2020 it does not work as expected)
