### ISSUE TITLE
ElunaCFBG A compiler error

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#159]
Current elunaCFBG operating system: Ubuntu16.04
Compile error:

[ 25%] Linking CXX executable vmap_extractor
[ 25%] Built target vmap_extractor
Scanning dependencies of target scripts
[ 26%] Building CXX object src/game/CMakeFiles/game.dir/PassiveAI.cpp.o
[ 26%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/__/GenLoader.cpp.o
[ 26%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/game/ScriptedEscortAI.cpp.o
[ 26%] Building CXX object src/game/CMakeFiles/game.dir/TotemAI.cpp.o
[ 27%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/game/ScriptedGuardAI.cpp.o
[ 27%] Building CXX object src/game/CMakeFiles/game.dir/GridNotifiers.cpp.o
[ 27%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/game/ScriptedCreature.cpp.o
[ 27%] Building CXX object src/game/CMakeFiles/game.dir/Unit.cpp.o
[ 27%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/game/ScriptedFollowerAI.cpp.o
[ 27%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/game/ScriptedSimpleAI.cpp.o
[ 27%] Building CXX object src/scripts/CMakeFiles/scripts.dir/Custom/CrossfactionBG/CrossfactionBG.cpp.o
/home/OregonCore-ElunaCFBGcustom/src/scripts/Custom/CrossfactionBG/CrossfactionBG.cpp: In member function ‘void CFBG::CFLeaveBattleGround(Player*)’:
/home/OregonCore-ElunaCFBGcustom/src/scripts/Custom/CrossfactionBG/CrossfactionBG.cpp:125:13: error: ‘class Player’ has no member named ‘InitDisplayIds’
     player->InitDisplayIds();
             ^
src/scripts/CMakeFiles/scripts.dir/build.make:206: recipe for target 'src/scripts/CMakeFiles/scripts.dir/Custom/CrossfactionBG/CrossfactionBG.cpp.o' failed
make[2]: *** [src/scripts/CMakeFiles/scripts.dir/Custom/CrossfactionBG/CrossfactionBG.cpp.o] Error 1
CMakeFiles/Makefile2:1041: recipe for target 'src/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/scripts.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 27%] Building CXX object src/game/CMakeFiles/game.dir/Position.cpp.o
[ 27%] Building CXX object src/game/CMakeFiles/game.dir/MapManager.cpp.o
[ 27%] Building CXX object src/game/CMakeFiles/game.dir/SpellAuras.cpp.o

[ 32%] Building CXX object src/game/CMakeFiles/game.dir/Bag.cpp.o
In file included from /home/OregonCore-ElunaCFBGcustom/src/game/LuaFunctions.cpp:24:0:
/home/OregonCore-ElunaCFBGcustom/src/game/PlayerMethods.h: In function ‘int LuaPlayer::SetGender(Eluna*, lua_State*, Player*)’:
/home/OregonCore-ElunaCFBGcustom/src/game/PlayerMethods.h:1652:17: error: ‘class Player’ has no member named ‘InitDisplayIds’
         player->InitDisplayIds();
                 ^
[ 32%] Building CXX object src/game/CMakeFiles/game.dir/Battleground.cpp.o
/home/OregonCore-ElunaCFBGcustom/src/game/Battleground.cpp:29:1: error: expected unqualified-id before ‘<<’ token
 <<<<<<<<< Temporary merge branch 1
 ^
src/game/CMakeFiles/game.dir/build.make:1190: recipe for target 'src/game/CMakeFiles/game.dir/Battleground.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Battleground.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/game/CMakeFiles/game.dir/build.make:1142: recipe for target 'src/game/CMakeFiles/game.dir/LuaFunctions.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/LuaFunctions.cpp.o] Error 1
CMakeFiles/Makefile2:982: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@VM-0-17-ubuntu:/home/OregonCore-ElunaCFBGcustom/build#

**Comment by talamortis** [comment]
Ok thank you, ill fix this today
