### ISSUE TITLE
Core crashes when using .npc add command

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#161]
Branch：ELunaCFBG
log file：
[log.tar.gz](https://github.com/talamortis/OregonCore/files/4792658/log.tar.gz)

**Comment by talamortis** [comment]
have you tested with master branch?

**Comment by yuanf225** [comment]
I test to confirm

**Comment by vhiperdev** [comment]
I CANNOT REPRODUCE THIS ERROR

Ubuntu 18

![image](https://user-images.githubusercontent.com/39068627/84967433-4aae6380-b0ea-11ea-83fa-7406430e9f24.png)

**Comment by yuanf225** [comment]
With OS: Ubuntu16, my elunacfbg branch is not 100% the same as tala's, so I used his master branch to verify

**Comment by yuanf225** [comment]
Sorry, this is my problem. I recently tried to transplant the Trinity_portal_master.SQL of Rochet2 into Oregon. I used the

**Comment by yuanf225** [comment]
Close this problem, this is caused by my wrong operation
