### ISSUE TITLE
Turn on debug mode to compile and report errors

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#166]
Branches: elunacfbg
Error message:
[100%] Linking CXX executable oregon-core
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
../../dep/lualib/liblualib.a(loslib.c.o): In function `os_tmpname':
/home/OregonCore/dep/lualib/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
src/oregoncore/CMakeFiles/oregon-core.dir/build.make:321: recipe for target 'src/oregoncore/oregon-core' failed
make[2]: *** [src/oregoncore/oregon-core] Error 1
make[2]: *** Deleting file 'src/oregoncore/oregon-core'
CMakeFiles/Makefile2:1176: recipe for target 'src/oregoncore/CMakeFiles/oregon-core.dir/all' failed
make[1]: *** [src/oregoncore/CMakeFiles/oregon-core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ekzobam** [comment]
Check your RAM when compile core in debug mode. There may not be enough RAM.

**Comment by ReyDonovan** [comment]
@talamortis show the full Clang log you showed a piece with a warning there is no information

**Comment by yuanf225** [comment]
Only this piece of information, I will try again after expanding the RAM
