### ISSUE TITLE
Eyes of the Beast (Hunter's spell)

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#168]
**Revision**:
b6076006
**Operating system**:
Win 7 64
**Current behavior**: 
When using a Eyes of the Beast (https://classic.wowhead.com/spell=1002/eyes-of-the-beast) spell, the pet can attacks standing with its back to the target.
If you move a certain distance from the player and the spell ends during the battle, this will cause the server to crash.
https://youtu.be/f5DbvYIBsjs

[4370+_oregon-core.exe_[14-6_19-0-36].txt](https://github.com/talamortis/OregonCore/files/4819398/4370%2B_oregon-core.exe_.14-6_19-0-36.txt)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Please test previous commit for crash issue has been resolved.

**Comment by yuanf225** [comment]
@CTPEJIOK84 Please test and verify，If you can’t verify it, I will verify it tomorrow

**Comment by CTPEJIOK84** [comment]
Сhecked, server crash resolved.

**Comment by yuanf225** [comment]
> 哎呀，服务器崩溃已解决。

@talamortis 
This problem has been fixed and can be turned off
