### ISSUE TITLE
Sulfuron Slammer

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#169]
**Revision**:
b607600
**Operating system**:
Win 7 64
**Current behavior**: 
When using the Sulfuron Slammer (https://www.wowhead.com/item=38466/sulfuron-slammer), only a visual effect appears, but no damage is caused.
https://www.youtube.com/watch?v=WShZ4AGAEWQ

**Expected behavior**: 
Must applies a buff causing you to take 4 fire damage every 3 seconds, for 6 seconds duration. 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/4211ca69a6105b4d8667120267e1b4477e53946a

Fixed by this commit
