### ISSUE TITLE
Smart_script problem with creature_text_locale

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#171]
**Revision**:
4376
**Operating system**:
Win 7 64
**Current behavior**: 
While core loading, localized text from creature_text_locale is also loaded. This is visible in core log file. But in game uses strings from creature_text. I do not know why.
![WoWScrnShot_062820_184147](https://user-images.githubusercontent.com/62596191/86004007-4f90e280-ba1b-11ea-9362-7a0b0bff12cf.jpg)

Add here not to do a new report.
When using emotion, for example /hello on creature, the game uses the non-localized name of the creature.
![WoWScrnShot_062820_194763](https://user-images.githubusercontent.com/62596191/86005781-ba431d80-ba1d-11ea-8108-1b8cc14cc778.jpg)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by wowtbconline** [comment]
I also want to solve this problem

**Comment by talamortis** [comment]
will look into it now, i only have english client though so not promising anything

**Comment by talamortis** [comment]
please check by imputting something into creature_ai_texts table as it might read from that.

Also make sure your server locale is set to the correct version and make sure you have the correct dbc files

**Comment by wowtbconline** [comment]
![Безымянный](https://user-images.githubusercontent.com/52467573/86006653-f6c34900-ba1e-11ea-948b-06bc8eb599a9.jpg)
Here I have this table, I translated it myself.

**Comment by wowtbconline** [comment]
Did you fill in the Russian localization?

**Comment by yuanf225** [comment]
https://github.com/yuanf225/OregonDB_Localised
FYI

**Comment by CTPEJIOK84** [comment]
I translated all the texts and filled in all the tables *locale.
The problem is not in server locale or dbc files - item names, creature names, spell names have the correct translation in the game.

**Comment by talamortis** [comment]
so you are no longer getting the error :/?

**Comment by CTPEJIOK84** [comment]
An error was detected after filling the tables :(

**Comment by CTPEJIOK84** [comment]
Checked creature_ai_texts, it uses translation strings.
