### ISSUE TITLE
“2020_04_18_keeping_the_enemy_at_bay.sql” Field error

### ISSUE THREAD

**Issue by mayaren888** [talamortis/OregonCore#174]
“smart_scripts” Table is not  ‘'event_param5'  
Execution error

![QQ图片20200703234221](https://user-images.githubusercontent.com/6006653/86483571-eac0e980-bd86-11ea-975b-c8348376b0bb.png)

db_error.log  ，“2020-07-03 23:21:22 Cannot execute file 2020_04_18_keeping_the_enemy_at_bay.sql, size: 2036: Unknown column 'event_param5' in 'field list'”

**Comment by talamortis** [comment]
Do not use the base world use the recent one from release
https://github.com/talamortis/OregonCore/releases/download/v1.0/database_17_11_19.zip

**Comment by mayaren888** [comment]
> Do not use the base world use the recent one from release
> https://github.com/talamortis/OregonCore/releases/download/v1.0/database_17_11_19.zip
oh，thank you very much!!
