### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#175]
**Revision**:
daf7087
**Operating system**:
Win7 64
**Current behavior**: 
After the commit daf7087 random server crashes appeared. The server crashes after the player crosses some places.
With commit 6b834f2 there is no such problem.
[4381_oregon-core.exe_[4-7_10-46-56].txt](https://github.com/talamortis/OregonCore/files/4872292/4381_oregon-core.exe_.4-7_10-46-56.txt)

**Steps to reproduce the problem**:
Go north from the Gurubashi arena along the road.
![Map](https://user-images.githubusercontent.com/62596191/86508617-2214b200-bdea-11ea-8f00-95c1bab108f0.PNG)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Thanks, will fix now
