### ISSUE TITLE
NPCs with waypoints from waypoint_data

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#176]
**Revision**:
daf7087
**Operating system**:
Win7 64
**Current behavior**: 
All NPCs, using paths from waypoint_data, start moving only if they are at a distance of visibility from the player. 
If the NPC begins to move and the player moves away from it by a distance of visibility, the NPC stops.

For example, when completing the quest Sigil of Arathor (https://classic.wowhead.com/quest=643/sigil-of-arathor), it is useless to look for a Lieutenant Valorcall (https://classic.wowhead.com/npc=2612/lieutenant-valorcall) on the road on which he patrols.
He can only be found at the his spawn poin.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
This is because you have Grid `Unload` enabled in the config.

this feature saves resources on host so it doesn't have to keep the grid open for it to work. and not waste resources on a certain grid if a player is not in that area.

**Comment by CTPEJIOK84** [comment]
Thank you very much for your answer. I'll look at the config.
