### ISSUE TITLE
Hunter's talents (Focused Fire, Spirit Bond) and Tracking spells

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#177]
**Revision**:
a1c891c
**Operating system**:
Win7 64
**Current behavior**: 
If you pick talent Focused Fire (https://tbcdb.com/?spell=35029) or Spirit Bond (https://tbcdb.com/?spell=19578) and your pet is summoned, any tracking spells (Track Humanoids https://classic.wowhead.com/spell=19883/track-humanoids, for example) no longer work. 
Video- https://youtu.be/YhbwenCLX5Y
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Will look into this issue tomorrow
