### ISSUE TITLE
Core commands ".modify demorph" and "cheat explore"

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#181]
**Revision**:
6bf04d8
**Operating system**:
Win7 64
**Current behavior**: 
Command ".modify demorph" work only with players but not work with NPCs.
Command ".cheat explore 1" reveal all maps, but command ".cheat explore 0" not hide them.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/a77d2f18ee53521ab79b0a0ab02f4f5ddfcfd9d3
