### ISSUE TITLE
Area spell damage to allied players

### ISSUE THREAD

**Issue by d3athbl0w** [talamortis/OregonCore#182]
**Describe the bug**

Users with area spells can damage allied players

**To Reproduce**
1. Arcane explosion is an example

**Expected behavior**

**Video**

https://www.youtube.com/watch?v=4ep7wqo8HR0

**Branch**
 master

**Additional context**

**AC HASH/COMMIT:**
a1c891c66cc3ab36200f0862e9d5c44ee9582b0b

**Comment by talamortis** [comment]
Does this only happen in battlegrounds?

**Comment by PadreWoW** [comment]
This is very old bug:
https://github.com/OregonCore/OregonCore/issues/1559
https://github.com/OregonCore/OregonCore/issues/1636

**Comment by d3athbl0w** [comment]
@talamortis happen in all world

**Comment by talamortis** [comment]
Thank you, I have tested and can confirm this is a bug. I will look into it shortly.

**Comment by talamortis** [comment]
@d3athbl0w & @PadreWoW please test the latest commit and let me know :)

**Comment by PadreWoW** [comment]
Not fixed

![image](https://user-images.githubusercontent.com/6802530/87881273-dfb1be80-ca00-11ea-8f06-47b6f26b24b4.png)

**Comment by PadreWoW** [comment]
catastrophe......

![image](https://user-images.githubusercontent.com/6802530/87881352-5949ac80-ca01-11ea-8828-617e371f79ee.png)

**Comment by talamortis** [comment]
did you pull the latest updates from today
![image](https://user-images.githubusercontent.com/6143065/87881902-657b3d00-c9f4-11ea-9bd1-ad3f584add59.png)

**Comment by PadreWoW** [comment]
ohhhh with last commits all fine
I wrote my answer before you put the commit here :)

**Comment by yuyu-lovegelin111333** [comment]
> ohhhh with last commits all fine I wrote my answer before you put the commit here :)

I do test in this year 2022's core ,found Paladin's Consecration can not hit allies [this was correct ]
But also cannot hit neutrals creature ? even the creature already attacked Players , this spell still has not damaged to creature . 
see below pic.,link ： 
![图片](https://user-images.githubusercontent.com/63507617/156583886-438ef786-4df1-4853-98de-87e92903d81f.png)
