### ISSUE TITLE
OregonCore + OregonCore-Modules Run error

### ISSUE THREAD

**Issue by left3721** [talamortis/OregonCore#183]
OregonCore Crash Report
=======================

Linux (4.4.0-185-generic) #215-Ubuntu SMP Mon Jun 8 21:53:19 UTC 2020 x86_64
Date: 17-Jul-20_12:22:33
Version: OregonCore Rev: 1+ Hash: 744387a+ (Unix,little-endian)
Build Type: Debug
Compiler: GNU (or compatible)
ACE version: 6.3.3

Memory: 1910870016 / 8353030144 (22.8764% used)
SWAP:   0 / 1022357504 (0% used)

Coredump file MAY be available.
Caught deadly signal: SIGSEGV
Fault at 0x28 referenced from: 0x7ab48d: address not mapped to object

BackTrace Thread LWP 8996
=====================================
#0 0x7ab48d in World::GetModuleBoolConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) +0x6d
  from ./oregon-core
    at ??:0

#1 0xcff4da in AddBoss_AnnouncerScripts() +0xca
  from ./oregon-core
    at ??:0

#2 0xa85e59 in AddModuleScripts() +0x9
  from ./oregon-core
    at ??:0

#3 0x7b7a79 in AddScripts() +0x9
  from ./oregon-core
    at ??:0

#4 0x6b3cd5 in ScriptMgr::ScriptsInit() +0xe5
  from ./oregon-core
    at ??:0

#5 0x7b192d in World::SetInitialWorldSettings() +0x126d
  from ./oregon-core
    at ??:0

#6 0x68e4ab in Master::Run(bool) +0x1bb
  from ./oregon-core
    at ??:0

#7 0x66e10e in main +0x25e
  from ./oregon-core
    at ??:0

#8 0x7f21a3aed840 in __libc_start_main +0xf0
  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

#9 0x682239 in _start +0x29
  from ./oregon-core
    at ??:0

BackTrace Thread LWP 8999
=====================================
#0 0x7f21a3ea4360 in pthread_cond_wait +0xc0
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#1 0x7f21a5fc88b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0xd5
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#2 0x7f21a5fa1057 in ?? +0x9e057
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#3 0x7f21a5fabfed in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x2d
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#4 0xa796d6 in SqlDelayThread::run() +0x56
  from ./oregon-core
    at ??:0

#5 0xa80693 in ACE_Based::Thread::ThreadTask(void*) +0x53
  from ./oregon-core
    at ??:0

#6 0x7f21a6000f56 in ACE_OS_Thread_Adapter::invoke() +0xc6
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#7 0x7f21a3e9e6ba in __errno_location +0x76ba
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#8 0x7f21a3bd44dd in clone +0x6d
  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

BackTrace Thread LWP 8998
=====================================
#0 0x7f21a3ea4360 in pthread_cond_wait +0xc0
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#1 0x7f21a5fc88b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0xd5
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#2 0x7f21a5fa1057 in ?? +0x9e057
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#3 0x7f21a5fabfed in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x2d
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#4 0xa796d6 in SqlDelayThread::run() +0x56
  from ./oregon-core
    at ??:0

#5 0xa80693 in ACE_Based::Thread::ThreadTask(void*) +0x53
  from ./oregon-core
    at ??:0

#6 0x7f21a6000f56 in ACE_OS_Thread_Adapter::invoke() +0xc6
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#7 0x7f21a3e9e6ba in __errno_location +0x76ba
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#8 0x7f21a3bd44dd in clone +0x6d
  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

BackTrace Thread LWP 8997
=====================================
#0 0x7f21a3ea4360 in pthread_cond_wait +0xc0
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#1 0x7f21a5fc88b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0xd5
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#2 0x7f21a5fa1057 in ?? +0x9e057
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#3 0x7f21a5fabfed in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x2d
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#4 0xa796d6 in SqlDelayThread::run() +0x56
  from ./oregon-core
    at ??:0

#5 0xa80693 in ACE_Based::Thread::ThreadTask(void*) +0x53
  from ./oregon-core
    at ??:0

#6 0x7f21a6000f56 in ACE_OS_Thread_Adapter::invoke() +0xc6
  from /usr/lib/libACE-6.3.3.so
    at /usr/lib/libACE-6.3.3.so:0

#7 0x7f21a3e9e6ba in __errno_location +0x76ba
  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0

#8 0x7f21a3bd44dd in clone +0x6d
  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

Segmentation fault (core dumped)

**Comment by talamortis** [comment]
Please apply module sql files make sure you are not putting the oregoncore-modules into the module folder put the file of each module you want in there. Also please next time just upload a .txt file with crash.
