### ISSUE TITLE
Random server crush after teleportation using x32 build

### ISSUE THREAD

**Issue by CTPEJIOK84** [talamortis/OregonCore#193]
**Revision**:
70b06f2

**Operating system**:
Win7 64

**Current behavior**: 
Since commit 525f913 I have random server crashes after teleportation. I cannot find the problem dependency.
There is no such problem in a debug build.
This issue is also showed up in previous commits of the Eluna branch.

**Steps to reproduce the problem**:
Teleport several times in different locations. Server may crash after any teleportation.
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Is this teleported by command or is it teleported by summon (ingame)?

Also are you using Any modules?

Have you tried to disable the ELUNA and then see if the problem still exist ?

**Comment by CTPEJIOK84** [comment]
This problem exists only in x32 build, x64 build work fine.
Crush occurs after teleportation using commands (.go, .tele) or spells like 26373.
I am not using any modules.
ELUNA was not included in CMake. Or can ELUNA be disabled somehow else?

**Comment by talamortis** [comment]
Ok thanks will compile now in x32 and then test

**Comment by talamortis** [comment]
i have tested x32 bit and still no issue, have you pulled the latest updates? can anyone else confirm this issue??

**Comment by CTPEJIOK84** [comment]
Now I use x64 build and this problem no more actual for me. Seems to be only I have a problem with x32. The issue can be closed.
