### ISSUE TITLE
Battlegrounds errors

### ISSUE THREAD

**Issue by d3athbl0w** [talamortis/OregonCore#207]
**Describe the bug**
there are several problems with the BG's.
When a character is disconnected either by mistake from the internet or something else on the battleground, it takes him to where he was before entering the battleground but he remains on the battleground list, this may generate wow error.

**Modules**

CrossfactionBG ON but i tested without CFBG

**Video**

With crossfactionBG: https://youtu.be/NA1gNgu-cCU

Without CrossfactionBG: https://youtu.be/3wqa9l4kSpM

**Branch**
Master

**Eluna**
Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/bc9c135e924a3c9e07de20d9da7e663f2379b6a7

**Comment by talamortis** [comment]
Ok fixed
- Servers without CFBG will now be teleported back into the battleground upon logging back in (if battleground is available)
- Servers with CFBG upon logout will leave battleground and teleport back to the entry point

Please pull latest core update and cfbg from modules.
