### ISSUE TITLE
Dampen magic and amplify magic should not buf at the same time

### ISSUE THREAD

**Issue by LordPsyan** [talamortis/OregonCore#212]
Going to make this as simple as possible.
Spells 33946 and 33944 are dampen magic and amplify magic.
You should not be able to have both these spells active on you at the same time. one should cancel out the other.

I added entries in spell_group and spell_group_stack_rules but it did not fix it.

**Comment by talamortis** [comment]
Can confirm but dont have time to fully look into it yet, Will check on monday
