### ISSUE TITLE
  Coilfang Resevoir--Serpent Shrine Cavern--lurker_below

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#22]
**Revision**:95952a3 

**Operating system**:Cannot use fishing skills to summon BOSS

**Current behavior**: Calling method: Fishing in the pond, no matter how many levels can be fished, there is a certain probability of BOSS.
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by talamortis** [comment]
Going from WoWWiki this requires 300+ fishing skill
[](https://wow.gamepedia.com/The_Lurker_Below)

From a forum i read it only requires one
[](https://www.mmo-champion.com/threads/1168685-fishing-up-Lurker-Still-rquired)

I will go off the WoWWiki as im not 100% sure on this issue

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/42aa88dec87fef91da99d87a23b49f4cc26be63d
