### ISSUE TITLE
Core startup crash

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#222]
**Describe the bug**
I just pulled the latest update and the compilation worked, but it crashed on boot and the Oregoncore didn't start properly

Cmake configuration:
 cmake ../ -DCMAKE_INSTALL_PREFIX=/data/server/ -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=0 -DELUNA=1 -DWITH_COREDEBUG=1

**Eluna**
- [ ] Enabled

**DEbug**
- [ ] Enabled

**HASH/COMMIT:**
commit 5d6314944639f7f410e6256ea2ea21dc00ac06f4

[crash-log.txt](https://github.com/talamortis/OregonCore/files/5463943/crash-log.txt)

**Comment by talamortis** [comment]
Did you apply the new DB?

**Comment by yuanf225** [comment]
I'm going to try it tonight, I haven't had time to play games lately
