### ISSUE TITLE
Core and Auth Server Crash after startup

### ISSUE THREAD

**Issue by milestorme** [talamortis/OregonCore#227]
**Describe the bug**
The auth server and worldserver builds and starts but has a blank screen for a few seconds then auto closes

**To Reproduce**
1. git clone latest branch
2. start auth server

**Expected behavior**
auth server runs and accepts connections without closing

**Screenshots**
![samecc](https://user-images.githubusercontent.com/44911744/99033222-ab28ca80-25ce-11eb-9474-46dff29909de.png)

**Branch**
master

**Eluna**
- [1 ] Enabled
- [ ] Disabled

**Script**
n/a

**Crash**
[realmd.log](https://github.com/talamortis/OregonCore/files/5534970/realmd.log)

**Additional context**
Auth server working fine at rev https://github.com/talamortis/OregonCore/tree/f904f214a2afbfb91b54d08d788a676802614c16

**HASH/COMMIT:**
OregonCore Rev: 4622 Hash: c68aba01 (Win64,little-endian) [realm-daemon]

**Comment by Falstring** [comment]
I can confirm this. Literally spent a day trying to get it to work.

**Comment by talamortis** [comment]
Try using the new oregon-core.conf please

**Comment by milestorme** [comment]
Yes worldserver runs on new conf but with server still bugged and closes after startup even with new conf

**Comment by yuanf225** [comment]
indeed so
