### ISSUE TITLE
Dwarves have a Bug with Reputaion in Shattrath Factions

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#231]
**Describe the bug**
Dwarves have a Bug with Reputaion in Shattrath Factions

**To Reproduce**
1.  Create Dwarf
2.  Go to Shattrath City
3.  Complete the Quest "Allegiance to the Scryers"
4.  You will see double reputation decrease with Aldor, double reputation increase with Scryers (two different increases 3500 + 4235!) and huge reputation decrease with Sha'tar to Unfriendly!

**Expected behavior**
There should be only one reputation decrease with Aldor and NO reputation decrease with Sha'tar!

**Screenshots**

![изображение](https://user-images.githubusercontent.com/6802530/100733740-b27a1180-33df-11eb-8bc1-39b464d78f88.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**Script**

**Crash**

**Additional context**
Rate.Reputation.Gain = 1 in config!

**HASH/COMMIT:**

**Comment by milestorme** [comment]
Yes can confirm this

**Comment by talamortis** [comment]
is this just this quest or is it with all reputation?

**Comment by PadreWoW** [comment]
Fix:

UPDATE `world`.`quest_template` SET `RewRepFaction2` = '0' , `RewRepValue2` = '0' WHERE `entry` = '10551'; 
UPDATE `world`.`quest_template` SET `RewRepFaction2` = '0' , `RewRepValue2` = '0' WHERE `entry` = '10552';
