### ISSUE TITLE
Using commands in the console can cause the core to crash

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#237]
**Describe the bug**
 Using any command in the console will cause core to crash 

**To Reproduce**
1. Use the command to create an account
2. .account create $account $password
3. 
4. 

**Expected behavior**
 The command executes successfully, the core does not crash, and is correctly written to the database

**Eluna**
- [x] Enabled

**Crash**
oregon-core_4670_22-Dec-20_21_00_47.txt](https://github.com/talamortis/OregonCore/files/5730220/oregon-core_4670_22-Dec-20_21_00_47.txt

**HASH/COMMIT:**
 061645a

**Comment by milestorme** [comment]
no crash for me 

![nocrash](https://user-images.githubusercontent.com/44911744/103180328-ee25cf80-48e8-11eb-9cda-d6b32868182b.png)

**Comment by yuanf225** [comment]
I tried to compile again

**Comment by talamortis** [comment]
can not confirm
