### ISSUE TITLE
Spell Soulshatter (29858 & 32835) not working

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#239]
**Describe the bug**
Spell Soulshatter (29858 & 32835) not working

**To Reproduce**
1.  Enter combat with 2 players (Tank + Warlock)
2.  Cast 29858 or 32835
3.  No threat reduce

**Expected behavior**
Soulshatter should reduce Warlock's threat by 50%

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/731beec089deff8b5a30fc592a003717f2589aac

**Comment by talamortis** [comment]
Can anyone confirm this?
