### ISSUE TITLE
Task:fanatical verogo

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#24]
![微信图片_20190614223532](https://user-images.githubusercontent.com/43561197/59516825-c46aaa80-8ef4-11e9-858a-be65d8665f05.png)
The fanatical verogo never appeared and could not be killed
![微信图片_20190614](https://user-images.githubusercontent.com/43561197/59517118-6e4a3700-8ef5-11e9-9901-7531d002397c.png)

**Comment by yuanf225** [comment]
the creature is not in the creature table , its entry=3395

**Comment by talamortis** [comment]
closed by commit https://github.com/talamortis/OregonCore/commit/2c6ccf1c081c8e6bbb05517b6c501d29c01d0d39
