### ISSUE TITLE
Huge Totem Auras Range

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#242]
**Describe the bug**
Huge Totem Auras Range
More than Aura's RangeIndex

**To Reproduce**
1.  Create Shaman
2.  Add totems
3.  Use Strenght of Earth Totem for example
4.  Run away from totem
5.  You'll see - aura will fade only on 160 feet range, but should on 20

p.s all works fine in group!

**Expected behavior**
Aura should fade on RangeIndex

**Screenshots**

![image](https://user-images.githubusercontent.com/6802530/105720271-4b3a9280-5f34-11eb-80ec-3392ff3e0263.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/731beec089deff8b5a30fc592a003717f2589aac

**Comment by talamortis** [comment]
Think this is a Grid issue but I'm not 100% sure

**Comment by PadreWoW** [comment]
> 
> 
> Think this is a Grid issue but I'm not 100% sure

Maybe...but I fixed it (hack fix)

**Comment by talamortis** [comment]
What command is to check range of NPC?
