### ISSUE TITLE
No Proc Aura from Shaman's Stormstrike

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#249]
**Describe the bug**
No Proc Aura from Shaman's Stormstrike

**To Reproduce**
1. Create Shaman
2. Learn Talent Stormstrike and Dual Wield
3. Take two maces (for example)
4. Use Talent Stormstrike on any mob

**Expected behavior**
When you use Stromstrike on mob, there should appear debuff on mob, that increase NATURE SPELL DAMAGE on mob by 20% for 2 hits

**Screenshots**
![изображение](https://user-images.githubusercontent.com/6802530/118125438-a28b4280-b3ff-11eb-9e09-ffcc11d309ad.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/a96f1abd0a91db175874a666b48d97b0b63fa5cd

**Comment by PadreWoW** [comment]
p.s I did this:
UPDATE `world`.`spell_proc_event` SET `procFlags` = '16' , `CustomChance` = '100' WHERE `entry` = '17364';

Debuff appears and nature spell damage increased (i'm not shure if ONLY nature spell damage - may be all....)
But there is another problem - it should increase nature spell damage ONLY for 2 hits, but the number of charges does not decrease when spells hit 

![изображение](https://user-images.githubusercontent.com/6802530/118126283-cc913480-b400-11eb-88a2-122d16392bdc.png)

**Comment by talamortis** [comment]
I can not confirm this issue as stormstrike seems to be working as intended.

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/118378573-addf9900-b5cc-11eb-8dd1-36dad1e1f8c9.png)
![image](https://user-images.githubusercontent.com/6143065/118378577-b59f3d80-b5cc-11eb-9528-dc2c587ffdfa.png)

**Comment by PadreWoW** [comment]
> 
> 
> I can not confirm this issue as stormstrike seems to be working as intended.

Ok - was my error
I tried to fix another bug - Mage's Frost, Ice, Molten Armor
These armor should proc even mage is under shields, but they are not

I did this:

DELETE FROM `world`.`spell_proc_event` WHERE `entry` IN ('168', '7300', '7301', '7302', '7320', '10219', '10220', '27124', '30482');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('168', '0', '0', '0', '0', '1024', '0', '70', '0'); 
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('7300', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('7301', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('7302', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('7320', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('10219', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('10220', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('27124', '0', '0', '0', '0', '1024', '0', '70', '0');
INSERT INTO `world`.`spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES ('30482', '0', '0', '0', '0', '1024', '0', '0', '0');

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index d923bb03..abcd72a0 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -1191,6 +1191,10 @@ bool SpellMgr::IsSpellProcEventCanTriggeredBy(SpellProcEventEntry const* spellPr
             return false;
     }
 
+	// Mage Shields Proc Fix
+	if ((procFlags & PROC_FLAG_TAKEN_DAMAGE) || (procExtra & PROC_EX_ABSORB))
+		return true;
+
     // Always trigger for this
     if (EventProcFlag & (PROC_FLAG_KILLED | PROC_FLAG_KILL | PROC_FLAG_DONE_TRAP_ACTIVATION))
         return true;

But this is completely wrong
