### ISSUE TITLE
Assertion failed when players login

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#250]
**Describe the bug**
Assertion failed when players login (not all players!)

**To Reproduce**
1. Some players produce "Assertion failed" log, when login (I don't know why and how to reproduce)
2. You can see this log only in debug mode!

**Screenshots**
![image](https://user-images.githubusercontent.com/6802530/118969165-6f9ffc00-b975-11eb-98d7-f00522758e35.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/a96f1abd0a91db175874a666b48d97b0b63fa5cd

**Comment by talamortis** [comment]
This looks like you have your own custom scripts assigned. Please test repo without any other assigned scripts before making an issue.
