### ISSUE TITLE
ace.dll crash when try to reset all instances

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#251]
**Describe the bug**
ace.dll crash when try to reset all instances

**To Reproduce**
1. Go to ANY dungeon (not raid)
2. Enter dungeon and press .save
3. Get out of the dungeon and press .save
4. Try to push button "Reset all instances" - crash

**Screenshots**
Enter
![image](https://user-images.githubusercontent.com/6802530/119137759-d7c01200-ba49-11eb-8d83-28114631ce68.png)

Out
![image](https://user-images.githubusercontent.com/6802530/119138364-79476380-ba4a-11eb-9e1d-6ac3152ace69.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/a96f1abd0a91db175874a666b48d97b0b63fa5cd

**Comment by PadreWoW** [comment]
![image](https://user-images.githubusercontent.com/6802530/119144495-63896c80-ba51-11eb-8a8b-a180f0de9b41.png)

**Comment by PadreWoW** [comment]
I commented out this and no crash:

![image](https://user-images.githubusercontent.com/6802530/119145530-68025500-ba52-11eb-883a-6e7052f41318.png)

**Comment by PadreWoW** [comment]
Another hack fix:

diff --git a/src/server/game/LuaEngine/LuaEngine.cpp b/src/server/game/LuaEngine/LuaEngine.cpp
index 3575fa4f..119ae46e 100644
--- a/src/server/game/LuaEngine/LuaEngine.cpp
+++ b/src/server/game/LuaEngine/LuaEngine.cpp
@@ -1233,6 +1233,9 @@ void Eluna::FreeInstanceId(uint32 instanceId)
 {
     LOCK_ELUNA;
 
+	if (!IsEnabled())
+		return;
+
     for (int i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
     {
         auto key = EntryKey<Hooks::InstanceEvents>((Hooks::InstanceEvents)i, instanceId);

And disable Eluna in config

**Comment by talamortis** [comment]
can anyone confirm this issue?

**Comment by talamortis** [comment]
@PadreWoW This was fixed?

**Comment by PadreWoW** [comment]
> 
> 
> @PadreWoW This was fixed?

diff --git a/src/server/game/LuaEngine/LuaEngine.cpp b/src/server/game/LuaEngine/LuaEngine.cpp
index 3575fa4f..119ae46e 100644
--- a/src/server/game/LuaEngine/LuaEngine.cpp
+++ b/src/server/game/LuaEngine/LuaEngine.cpp
@@ -1233,6 +1233,9 @@ void Eluna::FreeInstanceId(uint32 instanceId)
 {
     LOCK_ELUNA;
 
+	if (!IsEnabled())
+		return;
+
     for (int i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
     {
         auto key = EntryKey<Hooks::InstanceEvents>((Hooks::InstanceEvents)i, instanceId);

**Comment by yuyu-lovegelin111333** [comment]
> Another hack fix:
> 
> diff --git a/src/server/game/LuaEngine/LuaEngine.cpp b/src/server/game/LuaEngine/LuaEngine.cpp index 3575fa4f..119ae46e 100644 --- a/src/server/game/LuaEngine/LuaEngine.cpp +++ b/src/server/game/LuaEngine/LuaEngine.cpp @@ -1233,6 +1233,9 @@ void Eluna::FreeInstanceId(uint32 instanceId) { LOCK_ELUNA;
> 
> * if (!IsEnabled())
> * ```
>     return;
>   ```
> * for (int i = 1; i < Hooks::INSTANCE_EVENT_COUNT; ++i)
>   {
>   auto key = EntryKeyHooks::InstanceEvents((Hooks::InstanceEvents)i, instanceId);
> 
> And disable Eluna in config

Hi, Sir : does here means close and disable all Eluna Engine and LUA.script ? in which config files to disable ? 
【I am a rookie ， 1st time to learn C++】
