### ISSUE TITLE
Crash in void TempSummon::UnSummon(uint32 msTime)

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#257]
**Describe the bug**
Crash in void TempSummon::UnSummon(uint32 msTime)
see screenshot

**To Reproduce**
1. Don't know exactly cause of this crash

**Screenshots**
![изображение](https://user-images.githubusercontent.com/6802530/127829553-b06cc483-844a-407e-b101-03ad2fb4e69d.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/b75c10c72cc09e746c27930a2cbd4334969599ad

**Comment by talamortis** [comment]
What spell was used?

**Comment by PadreWoW** [comment]
I don't know
I wasn't in game
I think this is unsummon some pets or totems (when player already not in game)

p.s There is no such part of code at all in Trinity for example 

![изображение](https://user-images.githubusercontent.com/6802530/127967911-0913e92c-f438-4827-82b9-be478fe04c7c.png)

**Comment by talamortis** [comment]
Yeah Looking at the code i cant see why that block is there.
