### ISSUE TITLE
Crash in RemoveFromGrid / RemoveFromMap

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#261]
**Describe the bug**
Crash in RemoveFromGrid / RemoveFromMap

**To Reproduce**
1.  Don't Know (I think crash appears when core try to remove corpse)

**Screenshots**
![изображение](https://user-images.githubusercontent.com/6802530/132987841-0f7f308b-77c1-4376-8036-3cea9c5c75d6.png)

![изображение](https://user-images.githubusercontent.com/6802530/132987849-e52d3791-3d53-491c-ae30-4e01cb369860.png)

![изображение](https://user-images.githubusercontent.com/6802530/132987866-10c28739-a31c-4f81-8dc0-06c4f52de614.png)

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/ac3976af00e9cf34ee1557e257604bad201d12d6

**Comment by PadreWoW** [comment]
YYUUUEEEEEHHEEE!!!!

I found crash!

1) Go to instance
2) Die there
3) Revive outside
4) Crash

**Comment by PadreWoW** [comment]
hmmmm It is not that simple
its not enough die-revive
you should die, and exit game until Grid Unload
then login and revive
This is TrinityCore similar problem
https://github.com/TrinityCore/TrinityCore/commit/a94bdd00a9f31dcd9e4134987531937ca57975d6

**Comment by talamortis** [comment]
fixed in https://github.com/talamortis/OregonCore/commit/5187b53439bec40d2a42c8ea2ad9e311113c0819
