### ISSUE TITLE
Looking for help .

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [talamortis/OregonCore#269]
**Describe the bug**
<Excuse U and others , I am rookies just want to learn how to build and compiling this OregonCore>

**To Reproduce**
1. Currently , May i ask where is the Full.DataBase for our OregonCore@talamortis? is there any link or Wiki support ?
2. Secondly , the original OregonCor/offical one , their wiki link also can not open , and their DataBase.ZIP【in the year 2018】was only DB Create Structure.sql after expand their ZIP data file . 

**Expected behavior**
<Latest or any  adaptering DB for our OregonCore@talamortis>

**Screenshots**
<Thanks and very appreciate for anyone can help me !>

**Branch**

**Eluna**
- [ ] Enabled
- [ ] Disabled

**Script**

**Crash**

**Additional context**

**HASH/COMMIT:**

**Comment by turbosnek** [comment]
Here is DB https://github.com/talamortis/OregonCore/releases/tag/v1.0

**Comment by yuyu-lovegelin111333** [comment]
> 

Thanks ,@turbosnek!

**Comment by yuyu-lovegelin111333** [comment]
Thanks ! Already compling released .  Thanks a lot ! 
















At 2022-02-22 22:51:48, "turbosnek" ***@***.***> wrote:

Here is DB https://github.com/talamortis/OregonCore/releases/tag/v1.0

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
