### ISSUE TITLE
Hunter's spell : Mark target ?"

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [talamortis/OregonCore#271]
**Describe the bug**
<The hunter's pet will rush out and attack target on its own, while Hunter Player just only use the spell to mark target.>
Hunter's Pet under 【Defense mode】

**To Reproduce**
1.  Hunter's Pet under 【Defense mode】
2.  Hunter Player does not make any damage by spell or attack .
3. Start chose any creature outdoor , use the spell Mark Target .
4. Pet run to target with attack .

**Expected behavior**
Original  behavior 1: <Pet should not run to attack target , if Hunter player just only use spell 'Mark Target.>
Original  behavior 2: <Pet should run to attack target , if player start use any spell with damage or attack damage.>

**Screenshots**
<Screenshots will upload later >

**Branch**
<this year 2022 >

**Eluna**
- [0] Enabled
- [1] Disabled

**Script**

**Crash**

**Additional context**
<! Screenshots will upload later->

**HASH/COMMIT:**

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/1580b10227a4ccfdf7d5f992bb3362058c6fe6e4

**Comment by yuyu-lovegelin111333** [comment]
Thanks , so much !
