### ISSUE TITLE
quest:sea lion trial

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#28]
![image](https://user-images.githubusercontent.com/43561197/59958231-bd83ff00-94d5-11e9-954b-17971196e1c4.png)

![image](https://user-images.githubusercontent.com/43561197/59958273-78ac9800-94d6-11e9-9241-23a0cf83a155.png)
Unable to sneak into the endless sea search quest items, this task is the druid's professional mission

**Comment by talamortis** [comment]
I am unable to reproduce this issue, i have managed to pick up all pendents and complete the quest

**Comment by yuanf225** [comment]
Underwater breathing time is too short, bubbles in the water can not be used

--------------原始邮件--------------
发件人："Lee "<notifications@github.com>;
发送时间：2019年6月22日(星期六) 晚上7:35
收件人："talamortis/OregonCore" <OregonCore@noreply.github.com>;
抄送："yuanf225 "<admin@itpel.com>;"Author "<author@noreply.github.com>;
主题：Re: [talamortis/OregonCore] quest:sea lion trial (#28)
-----------------------------------

 
I am unable to reproduce this issue, i have managed to pick up all pendents and complete the quest
