### ISSUE TITLE
Ingame Command Restarting Issue

### ISSUE THREAD

**Issue by Mowhok** [talamortis/OregonCore#3]
**Revision**:

**Operating system**:

**Current behavior**: 
.... ingame server restart lets oregoncore.exe has stopped working

**Expected behavior**: 
... server should shutdown and in a perfect world startup again

**Steps to reproduce the problem**:
.server restart 5 (ingame)
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
fixed in https://github.com/talamortis/OregonCore/commit/4464279516fbfd0758636597f235e238cca8c0a4
