### ISSUE TITLE
Abnormal biological attack

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#31]
![微信图片_20190627174819](https://user-images.githubusercontent.com/43561197/60256340-ea844780-9903-11e9-93a5-7e57f526f8a5.jpg)
![微信图片_20190627174831](https://user-images.githubusercontent.com/43561197/60256341-eb1cde00-9903-11e9-81da-2e3870e922cf.jpg)
![微信图片_20190627174839](https://user-images.githubusercontent.com/43561197/60256343-eb1cde00-9903-11e9-91f4-66777c18a28d.jpg)
![微信图片_20190627174847](https://user-images.githubusercontent.com/43561197/60256345-ebb57480-9903-11e9-99b8-9f9731857b72.jpg)
![微信图片_20190627174856](https://user-images.githubusercontent.com/43561197/60256346-ebb57480-9903-11e9-96fa-8e8ae500683d.jpg)
Creature's skill attack value is too high

**Comment by talamortis** [comment]
please provide more information - please remember i am English and i dont understand Chinese, these screen shots mean 0 to me :(

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/60280757-2932f580-9936-11e9-9c28-5a6551877b9e.png)
![image](https://user-images.githubusercontent.com/43561197/60280783-33ed8a80-9936-11e9-9818-f2cf23e01ed7.png)
The entry5847, 1097 ability has been found to do more than 10 million damage

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/60289757-1e189f00-990f-11e9-8001-1027e67f039a.png)
