### ISSUE TITLE
Abnormal pet attributes

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#32]
For example: kulmock
![微信图片_20190627180045](https://user-images.githubusercontent.com/43561197/60257161-85c9ec80-9905-11e9-84aa-9b7356cd77b8.jpg)

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/60280429-7febff80-9935-11e9-949d-b101d762c76e.png)
For example: kulmockk
I'm not sure if all pets have this high armor rating, or if it's just rare

**Comment by talamortis** [comment]
https://tbcdb.com/?npc=14491
Armor: 2,246, 
Health: 1,981
