### ISSUE TITLE
Mob not agressive

### ISSUE THREAD

**Issue by Pythol** [talamortis/OregonCore#35]
Area:
Bloodmyst İsle - Bloodcursed Isle

Mob: Bloodcursed Naga (only patrolling ones)

**Current behavior**: 
The patrolling "Bloodcursed Naga" are not attacking on sight

**Expected behavior**: 
Agressive

**Steps to reproduce the problem**:
Just walk by

**Comment by talamortis** [comment]
Can not reproduce, Maybe creature flag issue
