### ISSUE TITLE
Quest: Matis the Cruel

### ISSUE THREAD

**Issue by Pythol** [talamortis/OregonCore#36]
Location: Bloodmyst Isle

**Current behavior**: 
There is a friendly NPC named "Tracker of the Hand" at the spawn position of "Matis the Cruel" - you have to capture Matis but the npc is killing him.

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/789e67ed56100e05b4eeaa41a0d0669f654a978e
