### ISSUE TITLE
Quest: Electropellers

### ISSUE THREAD

**Issue by Pythol** [talamortis/OregonCore#38]
**Describe the bug**
Your task is to find the item called "Electropeller" - it can be found while fishing in the rivers and ponds of "Darkshore" - it seems that the item is missing.

**To Reproduce**
1. Fishing in a river or pond in Darkshore

**Expected behavior**
It is rare to find i guess but it should drop while catching fish.

**AC HASH/COMMIT:**
?

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/465c34a51f36755efab9634109430a2d07895057
