### ISSUE TITLE
[Script / boss] Selin Fireheart

### ISSUE THREAD

**Issue by talamortis** [talamortis/OregonCore#4]
**Revision**:

**Operating system**:
Windows 10

**Current behavior**: 
The whole encounter for Selin Fireheart is buggy, he casts one spell like every 2 seconds till he is out of mana he then runs to a crystal and thinks about what to do next.

**Expected behavior**: 

**Steps to reproduce the problem**:

Go MGT start encounter with 1st boss

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

NPC - ScriptName: Boss_selin_fireheart

**Comment by DanielBallaSZTE** [comment]
@talamortis 

https://github.com/talamortis/OregonCore/blob/master/src/scripts/EasternKingdoms/MagistersTerrace/boss_selin_fireheart.cpp#L250

According to this, the boss literally casts drain life, when the event begins, the server ticks, drain life continues, starts to cast Fel Explosion, at the end checks if he has enough mana, he casted fel explosion so interrupted drain life, but the drain life timer still goes on, so just spams fel explosion every 2 seconds until he runs out of mana, and goes to a crystal. Do I get it right? If so, and you haven't worked out a solution yet, I would be glad to fix this script.
EDIT:
If he had infinite amount of mana, when 10 seconds have passed, he would start again by casting drain life, but would get interrupted by fel explosion.

**Comment by talamortis** [comment]
This is why i have not closed the issue :P as i still need to rework him but if you want to rework him or fix the script please feel free and open a PR 👍

**Comment by DanielBallaSZTE** [comment]
@talamortis Also, would you mind throwing me an email in private? I can't see your email on your profile, 
however my email address is listed on mine I think. Would like to ask a question or two if you don't mind.

**Comment by talamortis** [comment]
you could always add me on discord speedfangz#6864

**Comment by DanielBallaSZTE** [comment]
Wait. I actually misunderstood the current script.
I just made some investigations, and found out that the boss' has the correct behaviour after all. Looks pretty "stupid" for a boss to do stuff like that, but if you read through [here](https://wow.gamepedia.com/Selin_Fireheart) and watch [this](https://www.youtube.com/watch?v=6bczeIDnbww) video (there are a lot other videos on youtube as well) you realise he's doing things right.

**Comment by talamortis** [comment]
Ok, if you say this is how the boss is supposed to be ill close the issue and mark it as invalid. Thanks
