### ISSUE TITLE
Hunter skill - adder sting

### ISSUE THREAD

**Issue by yuanf225** [talamortis/OregonCore#53]
Mana cannot be acquired from creatures with mana, skill does not work

**Comment by talamortis** [comment]
can you please provide the spell ID so i can test?

**Comment by yuanf225** [comment]
Just got home. Wait for me

**Comment by yuanf225** [comment]
spell ID:37551

**Comment by talamortis** [comment]
- This is a mana drain spell. This does not give the owner of the aura mana.
