### ISSUE TITLE
[Spell / Aura] Haunting Spirit [$20 awarded]

### ISSUE THREAD

**Issue by talamortis** [talamortis/OregonCore#58]
**Describe the bug**

haunting spirit aura that is applied in SKF keeps spawning the haunted souls.

**To Reproduce**
1. Go shadowfang keep
2.  Get debuff - Haunted spirit
3.  Wait for Proc
4. 

**Expected behavior**

Should only spawn one soul at a time 

**Screenshots**

**Additional context**

**AC HASH/COMMIT:**

**Comment by ELdoBA** [comment]
Thanks
