### ISSUE TITLE
Traitor Among Us (ID 27210)

### ISSUE THREAD

**Issue by knzpoo** [talamortis/OregonCore#59]
**Operating system**: Ubuntu 16

**Current behavior**:You should confront the "Deserter Agitator" (npc=23602), but they don't fight back and they run away from you.

Start the quest and initiate a fight against any one of the "Deserter Entiator". They will run away.

**Was expected a fight back**, like: https://www.youtube.com/watch?v=DHzve5DxV6s

The NPC in a place that he shouldn't be.
(https://user-images.githubusercontent.com/49311852/64138558-dc571980-cdd3-11e9-88a1-626c9dd640dd.png)

**Comment by talamortis** [comment]
can not reproduce, the only issue that i got with these are that they do not say 

"If you think you can stop us, you're mistaken, 'friend.'"

They have a chance of running away as being confronted and has a chance of attacking the player.
