### ISSUE TITLE
Quest/Class - Body and Heart [Druid]

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#67]
**Operating system:** Ubuntu 16

**Current behavior:** The quest [Body and Heart] 6001 and 6002
Druid class she's calling two LunaCraw

https://tbcdb.com/?quest=6001
https://tbcdb.com/?quest=6002

**Was expected to** Should sumon only one LunaClaw

**Comment by talamortis** [comment]
Fixed in https://github.com/talamortis/OregonCore/commit/8001c729e87a904470b400969f2dbaf9449a3274
