### ISSUE TITLE
Skill/Skinning - Creatures Not Drop Skinning

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#68]
**Operating system:** Ubuntu 16

**Current behavior:** Some creatures like wolves and bears aren't skinning with skinning

https://tbcdb.com/?npc=213#skinning
![image](https://user-images.githubusercontent.com/46387591/66705709-93fb1780-ed00-11e9-9a17-bea26a5d1cb9.png)

**Was expected to** About Skinning should get skinlot creature ID 213

**Comment by talamortis** [comment]
can not reproduce
