### ISSUE TITLE
Finding the Survivors Quest ID : 9948

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#72]
**Operating system**: Ubuntu 16

**Current behavior**: releasing the survivors nothing happens,
the mission doesn't end

**Was expected to** 
When releasing survivors count correctly

https://www.wowhead.com/quest=9948/finding-the-survivors

**Comment by PadreWoW** [comment]
UPDATE `world`.`quest_template` SET `ReqSpellCast1`='0' WHERE `entry`='9948';
UPDATE `world`.`creature` SET `spawntimesecs` = '60' WHERE `id` = '18428';
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900148','Help! Help! They`re going to eat me!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER1');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900149','The ogres have the keys! Kill the ogres and get me out of here!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER2');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900150','My children will be made orphans!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER3');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900151','One day, a hero will rise and lift the orcs up to their former glory.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER4');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900152','Many thanks, hero!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER5');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900153','Death to the ogres!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER6');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900154','Thank you! Your service to the  Mag`har  will not be forgotten.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER7');
INSERT INTO `world`.`script_texts`(`entry`,`content_default`,`content_loc1`,`content_loc2`,`content_loc3`,`content_loc4`,`content_loc5`,`content_loc6`,`content_loc7`,`content_loc8`,`sound`,`type`,`language`,`emote`,`comment`) VALUES ( '-1900155','Spirits watch over you!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0','0','SAY_PRISONER8');

/*#####
## go_maghar_prison & npc_maghar_prisoner
#####*/

enum
{
    QUEST_SURVIVORS       = 9948,
    NPC_MPRISONER         = 18428,

    SAY_MAG_PRISONER1     = -1900148,
    SAY_MAG_PRISONER2     = -1900149,
    SAY_MAG_PRISONER3     = -1900150,
    SAY_MAG_PRISONER4     = -1900151,
    SAYT_MAG_PRISONER1    = -1900152,
    SAYT_MAG_PRISONER2    = -1900153,
    SAYT_MAG_PRISONER3    = -1900154,
    SAYT_MAG_PRISONER4    = -1900155
};

struct npc_maghar_prisonerAI : public npc_escortAI
{
    npc_maghar_prisonerAI(Creature* pCreature) : npc_escortAI(pCreature) {}

    uint64 uiPlayerGUID;

    void Reset()
    {
        uiPlayerGUID = 0;
		SetRun();
    }

    void MoveInLineOfSight(Unit* pWho)
    {
        if (pWho->GetTypeId() == TYPEID_PLAYER && ((Player*)pWho)->GetReputationRank(941) >= REP_FRIENDLY && me->IsWithinDistInMap(((Player*)pWho), 20))
        {
            if (uiPlayerGUID == pWho->GetGUID())
                return;
            else uiPlayerGUID = 0;

            switch (urand(0, 3))
            {
            case 0:
                DoScriptText(SAY_MAG_PRISONER1, me);
                break;
            case 1:
                DoScriptText(SAY_MAG_PRISONER2, me);
                break;
            case 2:
                DoScriptText(SAY_MAG_PRISONER3, me);
                break;
            case 3:
                DoScriptText(SAY_MAG_PRISONER4, me);
                break;
            }
            uiPlayerGUID = pWho->GetGUID();
        }
    }

    uint32 WaypointID()
    {
        switch (me->GetGUIDLow())
        {
        case 65828:
            return 1;
            break;
        case 65826:
            return 1;
            break;
        case 65827:
            return 1;
            break;
        case 65825:
            return 1;
            break;
        case 65829:
            return 1;
            break;
        case 65823:
            return 2;
            break;
        case 65824:
            return 2;
            break;
        case 65821:
            return 2;
            break;
        case 65815:
            return 2;
            break;
        case 65814:
            return 3;
            break;
        case 65813:
            return 4;
            break;
        case 65819:
            return 5;
            break;
        case 65820:
            return 5;
            break;
        case 65817:
            return 6;
            break;
        case 65822:
            return 6;
            break;
        case 65816:
            return 6;
            break;
        case 65831:
            return 7;
            break;
        case 65832:
            return 7;
            break;
        case 65830:
            return 7;
            break;
        case 65818:
            return 8;
            break;
        default:
            return 1;
            break;
        }
    }

    void StartRun(Player* pPlayer)
    {
        switch (WaypointID())
        {
        case 1:
            AddWaypoint(0, -1076.000f, 8945.270f, 101.891f);
            AddWaypoint(1, -1087.469f, 8894.919f, 102.183f);
            Start(false, true, pPlayer->GetGUID());
            break;
        case 2:
            AddWaypoint(0, -782.796f, 8875.171f, 181.745f);
            AddWaypoint(1, -821.331f, 8913.110f, 171.417f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 3:
            AddWaypoint(0, -670.298f, 8810.587f, 196.057f);
            AddWaypoint(1, -717.270f, 8806.274f, 184.591f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 4:
            AddWaypoint(0, -710.969f, 8763.471f, 186.513f);
            AddWaypoint(1, -782.685f, 8874.755f, 181.740f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 5:
            AddWaypoint(0, -865.144f, 8713.610f, 248.041f);
            AddWaypoint(1, -880.415f, 8743.203f, 233.202f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 6:
            AddWaypoint(0, -847.285f, 8722.406f, 177.255f);
            AddWaypoint(1, -810.138f, 8731.109f, 178.226f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 7:
            AddWaypoint(0, -897.005f, 8689.280f, 170.527f);
            AddWaypoint(1, -844.252f, 8721.320f, 177.257f);
			Start(false, true, pPlayer->GetGUID());
            break;
        case 8:
            AddWaypoint(0, -838.047f, 8691.124f, 180.549f);
            AddWaypoint(1, -821.200f, 8712.569f, 182.702f);
			Start(false, true, pPlayer->GetGUID());
            break;
        }
        return;
    }

    void WaypointReached(uint32 uiPointId)
    {
        switch (uiPointId)
        {
        case 0:
            SetRun();
            break;
        case 1:
            me->ForcedDespawn();
            break;
        }
    }
};

CreatureAI* GetAI_npc_maghar_prisoner(Creature* pCreature)
{
    return new npc_maghar_prisonerAI(pCreature);
}
