### ISSUE TITLE
Natural Remedies - Quest ID 10351

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#80]
**Operating system**: Ubuntu 16

**Current behavior**: The natural remedies quest in hellfire peninsula is not working
Item doesn't summon mob it should summon

**Was expected to** https://www.youtube.com/watch?v=iGrljCsdOy4

**Comment by talamortis** [comment]
Fixed in this : https://github.com/talamortis/OregonCore/commit/d7989cd5cb5dfaf2eb6b7f181b24f42f31d45270
