### ISSUE TITLE
Shattered Sun Pendant of Might/Shattered Sun Pendant of Acumen and Idol of Terror ID's - 34679/34678 and 33509

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#81]
**Operating system**: Ubuntu 16

**Current behavior:** We noticed that both agi and spell power Shattered bugs are never looking for! and Idol of Terror does not breed either if you rain Mangle on npc rs 

**Was expected to** : 
should proc instead or another

**Comment by talamortis** [comment]
Please test https://github.com/talamortis/OregonCore/commit/16f191828d0215920da38613d23b903195a57a51

please post feedback on commit.
