### ISSUE TITLE
Track skill Bug

### ISSUE THREAD

**Issue by Forgivens** [talamortis/OregonCore#82]
Operating system: Ubuntu 18
Current behavior: When you use a class tracking skill and use a profession tracking skill. (example: Track Humanoids and then use Find Herbs) The second Tracking ability doesn't work and you can't switch to another tracking ability.
Was expected to: You use a tracking skill and when you use the next tracking skill it should change to the last one you used

**Comment by talamortis** [comment]
Im sorry i can not reproduce this bug, are you using the main oregoncore source or this branch?

**Comment by talamortis** [comment]
this got fixed https://github.com/talamortis/OregonCore/commit/d8104c06af06a69bd18ab6de9c9ec6c337a6d18d
