### ISSUE TITLE
Blink spell will go through any door/gate

### ISSUE THREAD

**Issue by coolzoom** [talamortis/OregonCore#88]
**Describe the bug**
Blink spell will go through any door/gate

**To Reproduce**
1. create a mage
2. ,learn 1953
3. .gm on
4. .go 703.891 544.47 112.654 564

**Expected behavior**
Blink spell should not go through gate/door

**Screenshots**

**Additional context**

**AC HASH/COMMIT:**

**Comment by yuanf225** [comment]
Mage flash ability?

**Comment by coolzoom** [comment]
> Mage flash ability?

right

**Comment by talamortis** [comment]
Fixed in https://github.com/talamortis/OregonCore/commit/c08c1772faa163f0bb96019ff2e65faaee20cbd2

**Comment by coolzoom** [comment]
thumb up!
