### ISSUE TITLE
Raid Gruul's Lair Boss - High King Maulgar  multiple bugs

### ISSUE THREAD

**Issue by auroralima** [talamortis/OregonCore#99]
**Operating system:** Ubuntu 18

**Current behavior :**
Multiple bugs is found when fighting the High King Maulgar, that's a lot of rs
First - Olm the Summoner, he summons 4 fellhunters at once, normal would only be 2, and the cd for this ability is practically nil, meaning he fills the fellhunter room in a short time, another problem with him is that he is blink all the time, (this never existed in your mechanics, not according to the guides and videos out there).
Second - Krosh Firehand.
This one has the same mistake as warlock, it keeps blinking constantly.
Third - Blindeye the Seer, this one is apparently normal.
Lastly Kiggler the Crazed - This one is also constantly blinking and unable to hold his aggro.

Boss High King Maulgar, apparently is normal.

How do we know that?
Wipe the ogres never back to their starting position! you reset the raid reset the servers and they are still there! lol
Some players managed to taunt only the boss (which was not supposed to be possible, the fight is to start with the 4).

If you need a test I will be happy to help :)

Links: https://wow.gamepedia.com/Gruul%27s_Lair

https://youtu.be/KkL99DH73qE
https://youtu.be/TPxA2Muxjtc
https://youtu.be/47tecoZwlGE

**Comment by auroralima** [comment]
Link video bug -  https://streamable.com/ggzht

SS's -
Once the wipe picks up, the ogres do not return to their positions.
and it's just the two ogres that are blinking.

https://cdn.discordapp.com/attachments/613780728529944592/659803405736214529/Screenshot_480.png

https://cdn.discordapp.com/attachments/613780728529944592/659803407556673586/Screenshot_481.png

**Comment by talamortis** [comment]
- [x] Orges to stop blinking
- [x] Orges to returning to "home positions"
- [x] Felhunters depawn after 60 seconds (this is a spell used by creature)
